# Site settings
author: Araba
title: Code Chronicles
header-img: img/home-bg.png
email: araba.taylor20@gmail.com
copyright_name: Araba
description: > # this means to ignore newlines until "baseurl:"
  Blog about Araba growing in her knowledge and application of coding.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  OkayAtay

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
